//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freya.WFEngine.TestApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Freya.WFEngine.TestApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Workflow&gt;
        ///  &lt;Activities&gt;
        ///    &lt;Add name=&quot;TransitionActivity&quot; type=&quot;Freya.WFEngine.TransitionActivity, Freya.WFEngine&quot; /&gt;
        ///  &lt;/Activities&gt;
        ///  &lt;Guards&gt;
        ///    &lt;Add name=&quot;RoleGuard&quot; type=&quot;Scio.CIS.RoleGuard, Scio.CIS&quot; /&gt;
        ///  &lt;/Guards&gt;
        ///  &lt;States&gt;
        ///    &lt;State name=&quot;First&quot;&gt;
        ///      &lt;TransitionActivity exitState=&quot;Second&quot; /&gt;
        ///    &lt;/State&gt;
        ///    
        ///    &lt;State name=&quot;Second&quot;&gt;
        ///      &lt;TransitionActivity exitState=&quot;First&quot;&gt;
        ///        &lt;RoleGuard roles=&quot;author;guarantee&quot; /&gt;    
        ///      &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
    }
}
